
name: Build and Deploy

on:
  push:
    branches: [main]

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: rg-3tier-aci-project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SUBSCRIPTION_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name acr3tieraciproject 

      - name: Build and push frontend image
        run: |
          docker build -t acr3tieraciproject.azurecr.io/frontend:${{ github.sha }} ./frontend
          docker push acr3tieraciproject.azurecr.io/frontend:${{ github.sha }}

      - name: Build and push backend image
        run: |
          docker build -t acr3tieraciproject.azurecr.io/backend:${{ github.sha }} ./backend
          docker push acr3tieraciproject.azurecr.io/backend:${{ github.sha }}

      - name: Update ACI frontend to new image
        run: |
          az container create \
            --name aci-frontend \
            --resource-group alams404 \
            --image acr3tieraciproject.azurecr.io/frontend:${{ github.sha }} \
            --registry-login-server acr3tieraciproject.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME}} \
            --registry-password ${{ secrets.ACR_PASSWORD}} \
            --dns-name-label aci-frontend-alams404 \
            --ports 80 \
            --os-type linux

      - name: Update ACI backend to new image
        run: |
          az container update \
            --name aci-backend \
            --resource-group alams404  \
            --image acr3tieraciproject.azurecr.io/backend:${{ github.sha }}

